site_name: VG Language Documentation
site_url: #/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  logo: assets/logo.png
  favicon: assets/logo.png
plugins:
  - search

nav:
  - Home: index.md
  - Introduction:
      - Overview: Introduction.md
      - Installation: Installation.md
      - Commands: Commands.md
  - Syntax:
      - Statements: Statements.md
      - Expressions: Expressions.md
      - Control Flow:
          - If Statements: if-statements.md
          - Loops:
              - For Loop: for-loop.md
              - While Loop: while-loop.md
              - Do-While Loop: do-while-loop.md
      - Variables:
          - Variable Declaration: Variables.md
          - Constants: Constants.md
      - Arrays: Arrays.md
      - Comments: Comments.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg